//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedLineLanka_Enterprise.Common.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parameter
    {
        public int ParameterID { get; set; }
        public string ParameterCode { get; set; }
        public string ParameterValue { get; set; }
    }
}
